# -*- coding: utf-8 -*-
"""Assn_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEV0pQoP3CXGuSIRl_toA61OulLiHONY

# Assignment  No. 08

# Problem Statement::
Data Visualization I
1. Use the inbuilt dataset 'titanic'. The dataset contains 891 rows and contains information about the passengers who boarded the unfortunate Titanic ship. Use the Seaborn library to see if we can find any patterns in the data.
2. Write a code to check how the price of the ticket (column name: 'fare') for each passenger is distributed by plotting a histogram.
"""

import seaborn as sns
import matplotlib.pyplot as plt

dataset = sns.load_dataset("titanic")
dataset.head()

dataset.describe()

sns.histplot(dataset['fare'])