# -*- coding: utf-8 -*-
"""Assn_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-du-KJAPQIBAlgD3ZV46PELEoi6ANar

# Assignment No 04

# Problem Statement :: Data Analytics I
Create a Linear Regression Model using Python/R to predict home prices using Boston Housing Dataset (https://www.kaggle.com/c/boston-housing). The Boston Housing dataset contains information about various houses in Boston through different parameters. There are 506 samples and 14 feature variables in this dataset.
The objective is to predict the value of prices of the house using the given features.

#importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
#Boston Dataset

"""#importing load_boston dataset from sklearn"""

boston = load_boston()

data = pd.DataFrame(boston.data)
data.head()

data['Price'] = boston.target
print(data)

x = boston.data
y = boston.target

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2,random_state = 0)

classifier = LinearRegression()
classifier.fit(xtrain, ytrain)

y_pred = classifier.predict(xtest)

plt.scatter(ytest, y_pred, c = 'green')
plt.xlabel("Price: in $1000's")
plt.ylabel("Predicted value")
plt.title("True value vs predicted value : Linear Regression")
plt.show()

mse = mean_squared_error(ytest, y_pred)
print("Mean Square Error : ", mse)