# -*- coding: utf-8 -*-
"""Assn_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtFyqDZHEvkp3pj_Rqg-AtBG2_2mHCIN

# Assignment No. 06

# Problem Statement :: Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Precision,
Recall on the given dataset.
"""

import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, recall_score, classification_report

df = pd.read_csv("Iris.csv")
df.head()

encoder = preprocessing.LabelEncoder()
df["Species"]=encoder.fit_transform(df["Species"])
df

x = df.iloc[:, [1, 4]].values
y = df.iloc[:, 5].values

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state = 0)

classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

ypred=classifier.predict(xtest)

confusion=confusion_matrix(ytest,ypred)
confusion

accuracy=accuracy_score(ytest,ypred)
print(accuracy)

precision=precision_score(ytest,ypred,average='micro')
print(precision)

recall=recall_score(ytest,ypred,average='micro')
recall