# -*- coding: utf-8 -*-
"""Assn_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HrH80aWxV88BV4txPoyMmcCYC7Amb3F

# Assignment No. 09

# Problem Statement :: Data Visualization II
Use the inbuilt dataset 'titanic' as used in the above problem.
1. Plot a box plot for distribution of age with respect to each gender along
with the information about whether they survived or not. (Column names : 'sex' and 'age')
2. Write observations on the inference from the above statistics.
"""

import seaborn as sns
import matplotlib.pyplot as plt

dataset = sns.load_dataset("titanic")
dataset.head()

sns.boxplot(x='sex', y='age', data=dataset)

sns.boxplot(x='sex', y='age', data=dataset, hue='survived')